ccflags-y += -Idrivers/bitmicro/include

obj-$(CONFIG_BITMICRO_POWER_SUPPLY)		+= bitmicro_power_supply.o
obj-$(CONFIG_BITMICRO_POWER_SUPPLY)		+= bitmicro_power_supply_attr.o

obj-$(CONFIG_GENERAL_POWER)				+= general_power/general_power.o
obj-$(CONFIG_GENERAL_POWER)				+= general_power/general_power_supply.o
obj-$(CONFIG_GENERAL_POWER)				+= general_power/general_power_upgrade.o

obj-$(CONFIG_P6_POWER)					+= p6_power/p6_power.o
obj-$(CONFIG_P6_POWER)					+= p6_power/p6_power_supply.o

obj-$(CONFIG_MEIC_POWER)				+= meic_power/meic_power.o
obj-$(CONFIG_MEIC_POWER)				+= meic_power/meic_power_supply.o
obj-$(CONFIG_MEIC_POWER)				+= meic_power/meic_power_upgrade.o

obj-$(CONFIG_HUNTKEY_POWER)				+= huntkey_power/huntkey_power.o
obj-$(CONFIG_HUNTKEY_POWER)				+= huntkey_power/huntkey_power_supply.o

obj-$(CONFIG_PMBUS_POWER)				+= pmbus_power/pmbus_power.o
obj-$(CONFIG_PMBUS_POWER)				+= pmbus_power/pmbus_power_core.o
obj-$(CONFIG_PMBUS_POWER)				+= pmbus_power/pmbus_power_driver.o
obj-$(CONFIG_PMBUS_POWER)				+= pmbus_power/pmbus_power_ops.o
obj-$(CONFIG_PMBUS_POWER)				+= pmbus_power/pmbus_power_upgrade.o

obj-$(CONFIG_DCDC_POWER)				+= dcdc_power/dcdc_power.o
obj-$(CONFIG_DCDC_POWER)				+= dcdc_power/dcdc_power_supply.o

