#!/bin/sh

system_dir="/root"
log_path="/dev/kmsg"

log() {
	echo [ramdisk]: $* >> ${log_path}
}

mount_part() {
	log "mount $1 on $2"
	mount -t ext4 -o data=journal $1 $2

	return $?
}

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs none /dev

log "======================ramdisk start===================="

exec < /dev/console > /dev/console 2>&1

# $1: the name of block device
wait_for_ready()
{
	CNT=10
	while true; do
		if [ -b $1 ]; then
			return 0
		fi
		
		log [$0]: Wait $1 ready ...
		
		CNT=`expr $CNT - 1`
		if [ $CNT -eq 0 ]; then
			log [$0]: $1 is not available!
			return 1
		fi
		sleep 1
	done
}

# $1: The block device
ubiattach /dev/ubi_ctrl -m 7
wait_for_ready /dev/ubi0
mount -o ro -t ubifs ubi0:rootfs $system_dir

ubiattach /dev/ubi_ctrl -m 8
wait_for_ready /dev/ubi1
mount -t ubifs ubi1:data /data

ubiattach /dev/ubi_ctrl -m 9
wait_for_ready /dev/ubi2
mount -t ubifs ubi2:data /data_bak


log "======================ramdisk end===================="

[ -x $system_dir/sbin/init ] && exec switch_root $system_dir /sbin/init
[ -x $system_dir/init ] && exec switch_root $system_dir /init
